export const CAREERS: any = [
  {
    position: 'CMO',
    company: 'Arwa',
    company_legal_name: 'Arwa Solutions',
    logo: '/images/careers/arwa-logo.jpeg',
    location: 'Kerala, India',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2024-03',
    end_date: null,
    industry: 'it services',
    link: 'https://arwaworld.com/',
    // responsibilities: [
    //   'Involved in the full-stack development of the Seeru B2B & B2C Online Travel Agency (OTA) web platform, focusing on scalable and efficient solutions.',
    //   'Collaborated closely with C-levels and cross-functional teams to design and implement user-friendly interfaces and backend services.',
    //   'Implemented responsive design principles to ensure a seamless experience across various devices and platforms.',
    // ],
  },
  {
    position: 'Frontend Engineer',
    company: 'Steyp',
    company_legal_name: 'Steyp Private Limited',
    logo: '/images/careers/steyp-logo.jpeg',
    location: 'Kerala, India',
    location_type: 'Hybrid',
    type: 'Full-time',
    start_date: '2022-01',
    end_date: '2024-03',
    industry: 'education',
    link: 'https://steyp.com/',
    responsibilities: [
      'Lead a team of 4 frontend engineers, enabling a superior developer experience and emphasizing new web features and performance improvements.',
      'Actively engaged in the entire development lifecycle, including requirements analysis, development, testing, deployment, maintenance, and continuous improvement.',
      'Determined project requirements, established work schedules, and delegated tasks to the team.',
      'Measured and monitored the performance of the web platform team to achieve company objectives and key results (OKRs).',
      'Conducted regular one-on-one sessions with the team, performed code reviews, and conducted user interviews.',
      'Maintained 7 frontend services, mostly in Next.js.',
      'Managed technical debt in the frontend codebase, handled bug fixes, and drove initiatives.',
      'Assisted the content team in enhancing SEO and increasing page coverage from 1K to over 5K.',
      "Implemented event tracking using Mixpanel and AppsFlyer to meet the marketing team's requirements.",
    ],
  },
  {
    position: 'Full Stack Engineer Internship',
    company: 'Talrop',
    company_legal_name: 'Talrop Private Limited',
    logo: '/images/careers/talrop-logo.jpeg',
    location: 'Kerala, India',
    location_type: 'Hybrid',
    type: 'Full-time',
    start_date: '2021-09',
    end_date: '2022-04',
    industry: 'education',
    link: 'https://talrop.com/',
    responsibilities: [
      'Involved in building the Sirka frontend web platform, primarily using Next.js.',
      'Developed well-written frontend code for new product features and maintained the codebase by fixing defects.',
      'Implemented web push notifications to handle incoming chat notifications.',
      'Improved the loading performance of the Sirka landing page and blog by reducing the Largest Contentful Paint (LCP) timing from 4.1s to 1.7s.',
      'Successfully migrated the frontend landing page codebase from Laravel to Next.js, resulting in a reduction in errors caused by faulty dependency resolutions.',
      'Migrated the Sirka Blog codebase from Laravel to WordPress CMS.',
    ],
  },
  {
    position: 'Full Stack Engineer Internship',
    company: 'Brototype',
    company_legal_name: 'Brototype',
    logo: '/images/careers/brototype-logo.png',
    location: 'Kerala, India',
    location_type: 'Hybrid',
    type: 'Full-time',
    start_date: '2021-07',
    end_date: '2021-10',
    industry: 'education',
    link: 'https://brototype.com/',
    responsibilities: [
      'Collaborated closely with stakeholders and internal teams to create products.',
      'Organized and facilitated meetings with clients, ensuring seamless project execution.',
      "Supervised the team's activities, fostering brainstorming sessions for business requirements.",
      "Harmonized the company's technological resources with its objectives.",
      "Contributed to the company's progress by consistently refining operations in alignment with its vision and mission.",
    ],
  },
];
