export const CAREERS: any = [
  {
    position: 'Software Engineer',
    company: 'SFO Technologies',
    company_legal_name: 'SFO Technologies Pvt. Ltd.',
    logo: '/images/careers/nest.png',
    location: 'Kochi, Kerala, India',
    location_type: 'On-site',
    type: 'Full-time',
    start_date: '2025-05',
    end_date: null,
    industry: 'it services',
    link: 'https://www.sfotechnologies.com/',
    responsibilities: [
      'Building an advanced employee tracking system covering attendance, movement tracking, leave management, and project progress monitoring.',
      'Developing the platform using Next.js for frontend and .NET for backend to ensure performance, reliability, and scalability.',
      'Designed and implemented a complete freight management system with modules for billing, invoicing, purchase orders, inward processing, role management, and vendor management.',
    ],
  },
  {
    position: 'Chief Technology Officer',
    company: 'Arwa World',
    company_legal_name: 'Arwa World',
    logo: '/images/careers/arwa-logo.jpeg',
    location: 'Kochi, Kerala, India',
    location_type: 'On-site',
    type: 'Full-time',
    start_date: '2024-03',
    end_date: '2025-04',
    industry: 'it services',
    link: 'https://arwaworld.com/',
    responsibilities: [
      "Led Arwa's technology strategy and end-to-end project execution with a focus on scalability and innovation.",
      'Delivered premium websites and software solutions for clients in Dubai across multiple industries.',
      'Managed a multidisciplinary team of developers and designers, ensuring high-quality and on-time delivery.',
      'Implemented modern technology stacks including Next.js, Django (Python), Node.js with Express, and Strapi.',
      'Played a key role in business development, client communication, and technical consulting to enhance client satisfaction.',
    ],
  },
  {
    position: 'Software Engineer',
    company: 'Steyp',
    company_legal_name: 'Steyp Private Limited',
    logo: '/images/careers/steyp-logo.jpeg',
    location: 'Kochi, Kerala, India',
    location_type: 'Hybrid',
    type: 'Full-time',
    start_date: '2022-04',
    end_date: '2024-03',
    industry: 'education',
    link: 'https://steyp.com/',
    responsibilities: [
      'Crafted captivating UIs for the Steyp e-learning platform, resulting in a remarkable 50% revenue surge by leveraging React, Next.js, Tailwind CSS, and cutting-edge frontend technologies.',
      'Orchestrated and motivated a cohesive team of 11 individuals, fostering effective teamwork and collaboration to achieve project milestones.',
      'Delivered immediate and responsive assistance within the platform to support learners in their coding journey in real time.',
      'Revolutionized the e-learning platform by introducing a feature that meticulously segregates day-to-day classes, significantly transforming the user experience.',
      'Elevated codebase quality through meticulous refactoring and improved application performance through strategic code splitting.',
      'Enhanced code quality, maintainability, and scalability by actively participating in and contributing to code reviews.',
    ],
  },
  {
    position: 'Software Engineer Intern',
    company: 'Steyp',
    company_legal_name: 'Steyp Private Limited',
    logo: '/images/careers/steyp-logo.jpeg',
    location: 'Kochi, Kerala, India',
    location_type: 'Hybrid',
    type: 'Internship',
    start_date: '2021-10',
    end_date: '2022-04',
    industry: 'education',
    link: 'https://steyp.com/',
    responsibilities: [
      'Designed React and SCSS-based UI for live projects, demonstrating front-end proficiency.',
      'Developed RESTful APIs using Python Django and Django Rest Framework.',
      'Conducted independent research to stay updated on full-stack development trends.',
      'Demonstrated leadership by training junior learners and fostering collaboration.',
    ],
  },
];
