import { DefaultSeoProps } from 'next-seo';

import {
  DEFAULT_OG_IMAGE,
  SITE_LOCALE,
  SITE_NAME,
  SITE_URL,
  TWITTER_HANDLE,
} from './site';
import { BLOG_TITLE_SUFFIX } from '../helpers/blog';
import { absoluteUrl } from '../libs/seo';
import { PERSON_ID } from '../libs/structured-data';
import type { BlogPostSummaryProps } from '../types/blog';
import { ProjectItemProps } from '../types/projects';
import { BuildSeoProps, PageSeoProps, SeoImageProps } from '../types/seo';

type StaticPageKey =
  | 'home'
  | 'about'
  | 'contact'
  | 'projects'
  | 'dashboard'
  | 'playground'
  | 'blog'
  | 'notFound';

// Single source of truth for static routes. Titles and descriptions must be
// unique across the site (enforced in src/__tests__/seo/seo.test.ts).
export const PAGE_SEO: Record<StaticPageKey, PageSeoProps> = {
  home: {
    path: '/',
    title: 'Awad Ali — Freelance Next.js & React Developer | Dubai & Europe',
    description:
      'Full-stack developer with 4+ years building Next.js, React and Node.js applications. I work with startups and companies across the UAE, the Gulf and Europe. GMT+5:30 — full overlap with Gulf and European hours.',
  },
  about: {
    path: '/about',
    title: 'About Awad Ali — Full-Stack Next.js & Node.js Developer',
    description:
      '4+ years building web products with Next.js, React and Node.js — from leading an 11-engineer team at Steyp to CTO at Arwa World, delivering for clients in Dubai.',
  },
  contact: {
    path: '/contact',
    title: 'Hire Awad Ali — Start Your Next.js or React Project',
    description:
      'Book a 30-minute call or send a message about your Next.js, React or Node.js project. I work on GMT+5:30, overlapping Gulf and European business hours.',
  },
  projects: {
    path: '/projects',
    title: 'Case Studies — Next.js & React Projects by Awad Ali',
    description:
      'Case studies of Next.js, React and Node.js builds: corporate websites for GCC companies Lazulite and Al Faris Group, the Steyp e-learning platform and DiagTools.',
  },
  dashboard: {
    path: '/dashboard',
    title: 'Developer Dashboard — GitHub Activity | Awad Ali',
    description:
      'My GitHub contribution calendar, pulled live from the GitHub API, alongside a summary of my LinkedIn profile.',
  },
  playground: {
    path: '/playground',
    title: 'JavaScript Playground — Run Code in the Browser | Awad Ali',
    description:
      'An interactive JavaScript playground to write, run, and experiment with code snippets directly in the browser.',
  },
  blog: {
    path: '/blog',
    title: 'Blog: Next.js, React and Node.js Articles | Awad Ali',
    description:
      'Practical articles on building fast, search-friendly web apps with Next.js, React and Node.js, drawn from real client projects. Written by Awad Ali.',
  },
  notFound: {
    path: '/404',
    title: 'Page Not Found | Awad Ali',
    description:
      "This page doesn't exist. Head back to the homepage, browse my projects, or get in touch about your project.",
    noindex: true,
  },
};

export const getProjectPageSeo = (project: ProjectItemProps): PageSeoProps => ({
  path: `/projects/${project.slug}`,
  title: `${project.title} Case Study | Awad Ali`,
  description: project.description,
});

type BlogSeoPost = Pick<
  BlogPostSummaryProps,
  | 'slug'
  | 'title'
  | 'excerpt'
  | 'coverImageUrl'
  | 'coverImageAlt'
  | 'publishedAt'
  | 'contentUpdatedAt'
  | 'readingMinutes'
  | 'category'
  | 'tags'
> & {
  seoTitle: string | null;
  seoDescription: string | null;
  canonicalUrl: string | null;
};

/**
 * The cover when there is one, otherwise a card generated by /api/og. The
 * version parameter changes whenever the words do, so social networks that
 * cache images by URL pick up a retitled post.
 */
export const getBlogSocialImage = (
  post: Pick<
    BlogPostSummaryProps,
    | 'slug'
    | 'title'
    | 'coverImageUrl'
    | 'coverImageAlt'
    | 'publishedAt'
    | 'contentUpdatedAt'
  >,
): SeoImageProps => {
  if (post.coverImageUrl) {
    return { url: post.coverImageUrl, alt: post.coverImageAlt || post.title };
  }
  const version = Date.parse(post.contentUpdatedAt ?? post.publishedAt);
  return {
    url: `/api/og?slug=${post.slug}&v=${version.toString(36)}`,
    width: 1200,
    height: 630,
    alt: post.title,
  };
};

export const getBlogPostSeo = (post: BlogSeoPost): BuildSeoProps => ({
  path: `/blog/${post.slug}`,
  title: `${post.seoTitle || post.title}${BLOG_TITLE_SUFFIX}`,
  description: post.seoDescription || post.excerpt,
  canonical: post.canonicalUrl || undefined,
  type: 'article',
  image: getBlogSocialImage(post),
  article: {
    publishedTime: post.publishedAt,
    modifiedTime: post.contentUpdatedAt ?? post.publishedAt,
    authors: [absoluteUrl('/about')],
    section: post.category?.name,
    tags: post.tags,
  },
  extraMetaTags: [
    { name: 'author', content: SITE_NAME },
    { name: 'twitter:label1', content: 'Written by' },
    { name: 'twitter:data1', content: SITE_NAME },
    { name: 'twitter:label2', content: 'Reading time' },
    { name: 'twitter:data2', content: `${post.readingMinutes} min read` },
  ],
});

type BlogListingSeoInput = {
  page: number;
  category?: { name: string; slug: string; description: string | null } | null;
  q?: string;
  tag?: string;
};

/**
 * Listing pages. Search results and tag filters are thin, near-duplicate
 * pages, so they stay out of the index while their links are still followed.
 * Later pages keep their own canonical and title rather than pointing at
 * page 1, so the posts linked only from them are still discovered.
 */
export const getBlogListingSeo = ({
  page,
  category,
  q,
  tag,
}: BlogListingSeoInput): PageSeoProps => {
  if (q) {
    return {
      path: `/blog?q=${encodeURIComponent(q)}`,
      title: `Search results for "${q}"${BLOG_TITLE_SUFFIX}`,
      description: `Blog posts by Awad Ali that match "${q}".`,
      noindex: true,
    };
  }
  if (tag) {
    return {
      path: `/blog?tag=${encodeURIComponent(tag)}`,
      title: `Posts tagged #${tag}${BLOG_TITLE_SUFFIX}`,
      description: `Blog posts by Awad Ali tagged ${tag}.`,
      noindex: true,
    };
  }

  const base = category
    ? {
        path: `/blog/category/${category.slug}`,
        label: `${category.name} Articles`,
        description:
          category.description ||
          `Articles about ${category.name} by Awad Ali, a freelance Next.js and React developer.`,
      }
    : {
        path: PAGE_SEO.blog.path,
        label: PAGE_SEO.blog.title.replace(BLOG_TITLE_SUFFIX, ''),
        description: PAGE_SEO.blog.description,
      };

  if (page <= 1) {
    return {
      path: base.path,
      title: `${base.label}${BLOG_TITLE_SUFFIX}`,
      description: base.description,
    };
  }
  return {
    path: `${base.path}?page=${page}`,
    title: `${base.label}, Page ${page}${BLOG_TITLE_SUFFIX}`,
    description: `${base.description} Page ${page}.`,
  };
};

// No canonical, og:url or description here on purpose: a site-wide default
// would leak onto every page that doesn't override it. The fallback image has
// no width/height for the same reason: they'd be attached to page images.
export const DEFAULT_SEO: DefaultSeoProps = {
  defaultTitle: SITE_NAME,
  openGraph: {
    type: 'website',
    locale: SITE_LOCALE,
    siteName: SITE_NAME,
    images: [
      {
        url: absoluteUrl(DEFAULT_OG_IMAGE.url),
        alt: DEFAULT_OG_IMAGE.alt,
      },
    ],
  },
  twitter: {
    handle: TWITTER_HANDLE,
    site: TWITTER_HANDLE,
    cardType: 'summary_large_image',
  },
};

// Moved unchanged from next-seo.config.js. Rebuilt as typed schema in Task 4.
export const personJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  // Blog posts point their author at this id, tying them to one Person.
  '@id': PERSON_ID,
  name: 'Awad Ali',
  url: SITE_URL,
  image: absoluteUrl(DEFAULT_OG_IMAGE.url),
  jobTitle: 'Full Stack Software Engineer',
  description:
    'Awad Ali is a full stack software engineer at SFO Technologies in Kochi, Kerala, building fast, scalable web apps with Next.js, React, Node.js and .NET.',
  email: 'mailtoawadali@gmail.com',
  worksFor: {
    '@type': 'Organization',
    name: 'SFO Technologies',
    url: 'https://www.sfotechnologies.com/',
  },
  address: {
    '@type': 'PostalAddress',
    addressLocality: 'Kochi',
    addressRegion: 'Kerala',
    addressCountry: 'IN',
  },
  sameAs: [
    'https://www.linkedin.com/in/awad-ali7/',
    'https://twitter.com/awadali91206435',
    'https://github.com/awadali7',
    'https://www.instagram.com/awadail.in',
  ],
  knowsAbout: [
    'Full Stack Development',
    'JavaScript',
    'TypeScript',
    'React',
    'Next.js',
    'Node.js',
    'Django',
    '.NET',
  ],
};
